// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMo9aZg1-zlGXCfp2Bft6o3MZaFwiv67Q',
    appId: '1:23963148123:web:e8f4ba7deb27c153cc847e',
    messagingSenderId: '23963148123',
    projectId: 'bbarna-6a725',
    authDomain: 'bbarna-6a725.firebaseapp.com',
    storageBucket: 'bbarna-6a725.appspot.com',
    measurementId: 'G-Q98CXXNQYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8zLIU0oXqZTIa-rQQ10LnK3V8bcEU9bU',
    appId: '1:23963148123:android:4bb4712f0860f8cbcc847e',
    messagingSenderId: '23963148123',
    projectId: 'bbarna-6a725',
    storageBucket: 'bbarna-6a725.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu-UZCzfoBHl1i0Z6GsPienVaZv160nqA',
    appId: '1:23963148123:ios:712d40b10b199220cc847e',
    messagingSenderId: '23963148123',
    projectId: 'bbarna-6a725',
    storageBucket: 'bbarna-6a725.appspot.com',
    iosBundleId: 'com.example.onlineCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu-UZCzfoBHl1i0Z6GsPienVaZv160nqA',
    appId: '1:23963148123:ios:712d40b10b199220cc847e',
    messagingSenderId: '23963148123',
    projectId: 'bbarna-6a725',
    storageBucket: 'bbarna-6a725.appspot.com',
    iosBundleId: 'com.example.onlineCourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMo9aZg1-zlGXCfp2Bft6o3MZaFwiv67Q',
    appId: '1:23963148123:web:8f64a24c0e9b0a17cc847e',
    messagingSenderId: '23963148123',
    projectId: 'bbarna-6a725',
    authDomain: 'bbarna-6a725.firebaseapp.com',
    storageBucket: 'bbarna-6a725.appspot.com',
    measurementId: 'G-CD45PHSL2B',
  );
}
